import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Add from '../components/Add'
import Backdrop from '../components/Backdrop'
import List from '../components/List'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [todo, setTodo] = useState('')
  const [list, setList] = useState([]);
  const [name, setName] = useState('')
  const [edit, setEdit] = useState(false)
  const [done, setDone] = useState('')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Today
        </h1>

        <Add todo={todo} setList={setList} setTodo={setTodo} list={list} />

        <List list={list} setList={setList} setName={setName} setEdit={setEdit} setDone={setDone} />

        <Backdrop name={name} done={done} edit={edit} />


      </main>
    </div>
  )
}

export default Home
