import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [todo, setTodo] = useState('')

  const [list, setList] = useState([
    { name: 'Surfar no Hawaii', id: 1 },
    { name: 'Andar de skate no Brazil', id: 2 },
    { name: 'Voar de balão', id: 3 },
  ]);

  const addTodo = (event: KeyboardEvent) => {

    if (event.key === 'Enter') {
      const time = new Date().getTime()

      setList([...list, { name: todo, id: time }]);

      setTodo('')
    }

  }

  useEffect(() => {
    console.log('list updated: ', list)
  }, [list])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Today
        </h1>

        <div className={styles.add}>
          <input type="text" value={todo} name="add" placeholder="Add a task to do" onKeyUp={addTodo} onChange={event => setTodo(event.target.value)} />
        </div>

        {list.map(({ name, id }) => (
          <div key={`item-${id}`}>
            <label htmlFor={`item-${id}`} className={styles.item}>
              <input type="checkbox" id={`item-${id}`} />
              {name}
            </label>
          </div>
        ))}

      </main>
    </div>
  )
}

export default Home
